name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  NEXT_PUBLIC_GHOST_API_URL: ''
  NEXT_PUBLIC_GHOST_API_KEY: ''
  INFURA_API_KEY: ''

jobs:
  ci:
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
    uses: ./.github/workflows/ci.yml
  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: changesets/action@v1
        id: changesets
        with:
          title: Release
          commit: Release
          version: yarn changeset version
          publish: yarn changeset publish
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
